package es.cifpcm.sakilars.model;
// Generated 26-ene-2018 13:14:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="sakila"
)
public class Payment  implements java.io.Serializable {


     private Short paymentId;
     private Customer customer;
     private Rental rental;
     private Staff staff;
     private BigDecimal amount;
     private Date paymentDate;
     private Date lastUpdate;

    public Payment() {
    }

	
    public Payment(Customer customer, Staff staff, BigDecimal amount, Date paymentDate, Date lastUpdate) {
        this.customer = customer;
        this.staff = staff;
        this.amount = amount;
        this.paymentDate = paymentDate;
        this.lastUpdate = lastUpdate;
    }
    public Payment(Customer customer, Rental rental, Staff staff, BigDecimal amount, Date paymentDate, Date lastUpdate) {
       this.customer = customer;
       this.rental = rental;
       this.staff = staff;
       this.amount = amount;
       this.paymentDate = paymentDate;
       this.lastUpdate = lastUpdate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="payment_id", unique=true, nullable=false)
    public Short getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Short paymentId) {
        this.paymentId = paymentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rental_id")
    public Rental getRental() {
        return this.rental;
    }
    
    public void setRental(Rental rental) {
        this.rental = rental;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="staff_id", nullable=false)
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }

    
    @Column(name="amount", nullable=false, precision=5)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="payment_date", nullable=false, length=19)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update", nullable=false, length=19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


