package es.cifpcm.sakilars.model;
// Generated 26-ene-2018 13:14:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="sakila"
    , uniqueConstraints = @UniqueConstraint(columnNames="user_name") 
)
public class Users  implements java.io.Serializable {


     private short userId;
     private String userName;
     private String password;
     private Set<Groups> groupses = new HashSet<Groups>(0);

    public Users() {
    }

	
    public Users(short userId, String userName, String password) {
        this.userId = userId;
        this.userName = userName;
        this.password = password;
    }
    public Users(short userId, String userName, String password, Set<Groups> groupses) {
       this.userId = userId;
       this.userName = userName;
       this.password = password;
       this.groupses = groupses;
    }
   
     @Id 

    
    @Column(name="user_id", unique=true, nullable=false)
    public short getUserId() {
        return this.userId;
    }
    
    public void setUserId(short userId) {
        this.userId = userId;
    }

    
    @Column(name="user_name", unique=true, nullable=false, length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="password", nullable=false, length=256)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="userses")
    public Set<Groups> getGroupses() {
        return this.groupses;
    }
    
    public void setGroupses(Set<Groups> groupses) {
        this.groupses = groupses;
    }




}


